const formattedSkillsMapping: { [key in string]: NFT_SKILLS_ENUM } = {
  // Arbalist
  "arrow-rain": "Arrow Rain",
  "quick-shot": "Quick Shot",
  "painstrike-gale": "Painstrike Gale",
  "illusion-arrow": "Illusion Arrow",
  "burst-shell": "Burst Shell",
  "flash-arrow": "Flash Arrow",
  "heavenly-bow": "Heavenly Bow",
  "minds-eye": "Mind's Eye",
  "ice-cage": "Ice Cage",
  "obliterate-shell": "Obliterate Shell",
  "venom-mist-shell": "Venom Mist Shell",
  "seeking-bolt": "Seeking Bolt",
  cloaking: "Cloaking",
  // Darkist
  asura: "Asura",
  "ghostly-flame": "Ghostly Flame",
  "infernal-abyss": "Infernal Abyss",
  "summon-craveling": "Summon Craveling",
  "sanguine-awakening": "Sanguine Awakening",
  "bursting-crimson-flowers": "Bursting Crimson Flowers",
  decay: "Decay",
  "chain-of-blood": "Chain of Blood",
  "eldritch-dragon-strike": "Eldritch Dragon Strike",
  annihilation: "Annihilation",
  backflow: "Backflow",
  terrify: "Terrify",
  "soul-dispersing-mist": "Soul Dispersing Mist",
  // Lancer
  "dragon-spear": "Dragon Spear",
  "ravaging-blow": "Ravaging Blow",
  "crescent-blade": "Crescent Blade",
  "nirvana-kick": "Nirvana Kick",
  "double-strike": "Double Strike",
  "sweeping-storm": "Sweeping Storm",
  "dragon-tail": "Dragon Tail",
  "ascending-dragon": "Ascending Dragon",
  "crushing-blow": "Crushing Blow",
  "wind-wall": "Wind Wall",
  "piercing-spear": "Piercing Spear",
  absorption: "Absorption",
  "blitz-strike": "Blitz Strike",
  // Sorcerer
  "dragon-tornado": "Dragon Tornado",
  "flame-orb": "Flame Orb",
  "frost-orb": "Frost Orb",
  "dark-vortex": "Dark Vortex",
  thunderstorm: "Thunderstorm",
  "magic-shield": "Magic Shield",
  blizzard: "Blizzard",
  "chain-lightning": "Chain Lightning",
  "flame-strike": "Flame Strike",
  "soul-devour": "Soul Devour",
  immolate: "Immolate",
  "vermilion-bird-embrace": "Vermilion Bird Embrace",
  "frozen-block": "Frozen Block",
  // Taoist
  "ray-of-light": "Ray of Light",
  "moonlight-wave": "Moonlight Wave",
  "sunbeam-sword": "Sunbeam Sword",
  "moonlight-orb": "Moonlight Orb",
  "rain-of-blades": "Rain of Blades",
  heal: "Heal",
  "piercing-blades": "Piercing Blades",
  "guardian-circle": "Guardian Circle",
  "tai-chi": "Tai Chi",
  "blasting-charm": "Blasting Charm",
  "soaring-slash": "Soaring Slash",
  "expulsion-circle": "Expulsion Circle",
  "greater-heal": "Greater Heal",
  // Warrior
  "dragon-flame": "Dragon Flame",
  "void-slash": "Void Slash",
  "splitting-slash": "Splitting Slash",
  "body-check": "Body Check",
  "ground-smash": "Ground Smash",
  "gale-slash": "Gale Slash",
  "lions-roar": "Lion's Roar",
  riposte: "Riposte",
  "iron-shackle": "Iron Shackle",
  "crescent-strike": "Crescent Strike",
  rampant: "Rampant",
  "barbaric-charge": "Barbaric Charge",
  "unbreakable-stance": "Unbreakable Stance",
}

export default formattedSkillsMapping
