export const WarriorSkills: NFT_SKILLS_ENUM[] = [
  "Dragon Flame",
  "Void Slash",
  "Splitting Slash",
  "Body Check",
  "Ground Smash",
  "Gale Slash",
  "Lion's Roar",
  "Riposte",
  "Iron Shackle",
  "Crescent Strike",
  "Rampant",
  "Barbaric Charge",
  "Unbreakable Stance",
];
export const SorcererSkills: NFT_SKILLS_ENUM[] = [
  "Dragon Tornado",
  "Flame Orb",
  "Frost Orb",
  "Dark Vortex",
  "Thunderstorm",
  "Magic Shield",
  "Blizzard",
  "Chain Lightning",
  "Flame Strike",
  "Soul Devour",
  "Immolate",
  "Vermilion Bird Embrace",
  "Frozen Block",
];
export const TaoistSkills: NFT_SKILLS_ENUM[] = [
  "Ray of Light",
  "Moonlight Wave",
  "Sunbeam Sword",
  "Moonlight Orb",
  "Rain of Blades",
  "Heal",
  "Piercing Blades",
  "Guardian Circle",
  "Tai Chi",
  "Blasting Charm",
  "Soaring Slash",
  "Expulsion Circle",
  "Greater Heal",
];
export const ArbalistSkills: NFT_SKILLS_ENUM[] = [
  "Arrow Rain",
  "Quick Shot",
  "Painstrike Gale",
  "Illusion Arrow",
  "Burst Shell",
  "Flash Arrow",
  "Heavenly Bow",
  "Mind's Eye",
  "Ice Cage",
  "Obliterate Shell",
  "Venom Mist Shell",
  "Seeking Bolt",
  "Cloaking",
];
export const LancerSkills: NFT_SKILLS_ENUM[] = [
  "Dragon Spear",
  "Ravaging Blow",
  "Crescent Blade",
  "Nirvana Kick",
  "Double Strike",
  "Sweeping Storm",
  "Dragon Tail",
  "Ascending Dragon",
  "Crushing Blow",
  "Wind Wall",
  "Piercing Spear",
  "Absorption",
  "Blitz Strike",
];

export const DarkistSkills: NFT_SKILLS_ENUM[] = [
  "Asura",
  "Ghostly Flame",
  "Infernal Abyss",
  "Summon Craveling",
  "Sanguine Awakening",
  "Bursting Crimson Flowers",
  "Decay",
  "Chain of Blood",
  "Eldritch Dragon Strike",
  "Annihilation",
  "Backflow",
  "Terrify",
  "Soul Dispersing Mist",
];

export const SkillsListByClass: { [key in 1 | 2 | 3 | 4 | 5 | 6]: NFT_SKILLS_ENUM[] } =
  {
    1: WarriorSkills,
    2: SorcererSkills,
    3: TaoistSkills,
    4: ArbalistSkills,
    5: LancerSkills,
    6: DarkistSkills,
  };
